theme: jekyll-theme-minimal
left-title: 基本信息
base-info: 🎉：黄添豪 男 1999-11 23岁
email: 📧：920240746@qq.com
educational-background: 🏫：广西外国语学院 软件工程 2023届
leetcode: https://leetcode.cn/u/xiaoyetan
github: https://github.com/xiaoyetanQAZ
